info:
  name: Create a new application as user
  type: http
  seq: 4

http:
  method: POST
  url: "{{host}}/api/applications"
  headers:
    - name: Authorization
      value: Bearer {{token}}
  body:
    type: multipart-form
    data:
      - name: category_id
        type: text
        value: "1"
      - name: values[1]
        type: text
        value: Alpaca.co
      - name: values[2]
        type: file
        value:
          - /Users/stamp/Uni-Ku-3/sem-2/DevOp/Project/Application Creation Test/Pichaphop-Resume.pdf
      - name: values[3]
        type: file
        value:
          - /Users/stamp/Uni-Ku-3/sem-2/DevOp/Project/Application Creation Test/SOP-Pichaphop.pdf
      - name: values[4]
        type: file
        value:
          - /Users/stamp/Uni-Ku-3/sem-2/DevOp/Project/Application Creation Test/Transcript-Pichaphop.pdf
      - name: attachments[]
        type: text
        value: ""
      - name: attachments[]
        type: text
        value: ""
  auth: inherit

runtime:
  variables:
    - name: token
      value: 7|weV4z62VSA5H9LqWIjHwpGEFPoNurTcA975I93ER9f432bea

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
