info:
  name: Create a new application as admin user
  type: http
  seq: 4

http:
  method: POST
  url: "{{host}}/api/applications"
  headers:
    - name: Authorization
      value: Bearer {{token}}
  body:
    type: multipart-form
    data:
      - name: category_id
        type: text
        value: "1"
      - name: values[1]
        type: text
        value: Alpaca.co
      - name: values[2]
        type: file
        value:
          - /Users/stamp/Uni-Ku-3/sem-2/DevOp/Project/Application Creation Test/Pichaphop-Resume.pdf
      - name: values[3]
        type: file
        value:
          - /Users/stamp/Uni-Ku-3/sem-2/DevOp/Project/Application Creation Test/SOP-Pichaphop.pdf
      - name: values[4]
        type: file
        value:
          - /Users/stamp/Uni-Ku-3/sem-2/DevOp/Project/Application Creation Test/Transcript-Pichaphop.pdf
      - name: attachments[]
        type: file
        value:
          - /Users/stamp/Uni-Ku-3/sem-2/schegan-visa-business.pdf
      - name: attachments[]
        type: file
        value:
          - /private/var/folders/wz/yqds9q7n11l30trf_v5cpp_h0000gn/T/TemporaryItems/com.apple.Photos.NSItemProvider/uuid=84FECC06-391D-4444-80D9-710B07725EA5&code=001&library=1&type=1&mode=1&loc=true&cap=true.jpeg/Photo on 23-7-2568 BE at 19.21.jpeg
  auth: inherit

runtime:
  variables:
    - name: token
      value: ""

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
