info:
  name: Get all applications by user id
  type: http
  seq: 13

http:
  method: GET
  url: "{{host}}/api/applications/user/{{id}}"
  body:
    type: json
    data: ""
  auth: inherit

runtime:
  variables:
    - name: id
      value: "50"

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
