info:
  name: Get all applications
  type: http
  seq: 1

http:
  method: GET
  url: "{{host}}/api/applications"
  auth: inherit

runtime:
  variables:
    - name: host
      value: localhost

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
