info:
  name: Get applications for asscoiate dean
  type: http
  seq: 6

http:
  method: GET
  url: "{{host}}/api/applications/associate-dean"
  headers:
    - name: Accept
      value: application/json
    - name: Content-Type
      value: application/json
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
