info:
  name: Get applications for asscoiate dean
  type: http
  seq: 6

http:
  method: GET
  url: ""
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
