info:
  name: Get applications for head of department
  type: http
  seq: 5

http:
  method: GET
  url: "{{host}}/api/applications/head-of-dept"
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
