info:
  name: Get applications for dean
  type: http
  seq: 7

http:
  method: GET
  url: "{{host}}/api/applications/associate-dean"
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
