info:
  name: Get approved applications form committee
  type: http
  seq: 9

http:
  method: GET
  url: "{{host}}/api/applications/approved"
  headers:
    - name: Accept
      value: application/json
    - name: Content-Type
      value: application/json
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
