info:
  name: Get applications for committee
  type: http
  seq: 8

http:
  method: GET
  url: "{{host}}/api/applications/committee?Accept=application/json&Content-Type=application/json"
  params:
    - name: Accept
      value: application/json
      type: query
    - name: Content-Type
      value: application/json
      type: query
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
