info:
  name: Get approved applications form committee
  type: http
  seq: 9

http:
  method: GET
  url: ""
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
