info:
  name: Get applications for committee
  type: http
  seq: 8

http:
  method: GET
  url: "{{host}}/api/applicatoins/committee"
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
