info:
  name: Get rejected applications
  type: http
  seq: 10

http:
  method: GET
  url: "{{host}}/api/applications/rejected"
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
